import React, { useState, useEffect } from 'react';

const Home = () => {
    return (
        <>
            <h1>this is the Home component</h1>
            <div className="container main-content">
                <h1>this is the main content section</h1>
                <p>MAIN CONTENT SECTION 1</p>
                <p>Cupidatat anim nisi magna aliquip dolore est. Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.</p>
                <hr/>
                <p>MAIN CONTENT SECTION 2</p>
                <p>Cupidatat anim nisi magna aliquip dolore est. Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.</p>
                <hr/>
                <p>MAIN CONTENT SECTION 3</p>
                <p>Cupidatat anim nisi magna aliquip dolore est. Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.Labore dolor exercitation adipisicing fugiat anim sit veniam quis.</p>
            </div>
        </>
    );
}

export default Home;